spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: paascloud-provider-customer
          uri: lb://paascloud-provider-customer
          predicates:
            - Path=/customer/**
          filters:
            - StripPrefix=1
  main:
    allow-bean-definition-overriding: true